export { ArrayConstructor as Array } from './Array'
export { BooleanConstructor as Boolean } from './Boolean'
export { FunctionConstructor as Function } from './Function'
export { NumberConstructor as Number } from './Number'
export { ObjectConstructor as Object } from './Object'
export { StringConstructor as String } from './String'
