export * as array from './array'
export * as boolean from './boolean'
export * as function from './function'
export * as number from './number'
export * as object from './object'
export * as string from './string'
